/*
  Practica 2 - Jenkinsfile dummy (PUNTO DE PARTIDA)

  Este Jenkinsfile es intencionalmente simple. En la Practica 2 iras anadiendo
  piezas (stages, agents, funciones Groovy, Docker build, docker compose, etc.)
  hasta construir un pipeline CI/CD completo.
*/

pipeline {
  // `agent any` = el pipeline se ejecuta en cualquier nodo/agente disponible.
  agent any

  stages {
    stage('Test') {
      agent {
        docker {
          image 'maven:3.8.6-openjdk-11-slim'
        }
      }
      steps {
      	sh 'pip install -r requirements.txt'
        sh 'pytest'
      }
    }
  }
}
